### ISSUE TITLE
Error Starting Inlfuxdb3

### ISSUE THREAD

**Issue by CSMarquez** [InfluxCommunity/TIG-Stack-using-InfluxDB-3-Core#1]
I am having this error every time I perform the procedure and it won't let me launch InfluxDB 3 Core

2025-02-17 10:01:54 Usage: influxdb3 serve [OPTIONS] --node-id <NODE_IDENTIFIER_PREFIX>
2025-02-17 10:01:54 
2025-02-17 10:01:54 For more information, try '--help'.
2025-02-17 10:01:55 error: unexpected argument '--writer-id' found
2025-02-17 10:01:55 
2025-02-17 10:01:55 Usage: influxdb3 serve [OPTIONS] --node-id <NODE_IDENTIFIER_PREFIX>
2025-02-17 10:01:55 
2025-02-17 10:01:55 For more information, try '--help'.
2025-02-17 10:01:55 error: unexpected argument '--writer-id' found
2025-02-17 10:01:55 
2025-02-17 10:01:55 Usage: influxdb3 serve [OPTIONS] --node-id <NODE_IDENTIFIER_PREFIX>
2025-02-17 10:01:55 
2025-02-17 10:01:55 For more information, try '--help'.
2025-02-17 10:01:56 error: unexpected argument '--writer-id' found

**Comment by deni-begaj** [comment]
Same here!

**Comment by Nejat** [comment]
> Same here! Checked the official documentation for v3 and used `--node-id node0` instead of writter_id. Seems to work.

i had the same problem, this fix worked for me

**Comment by suyashcjoshi** [comment]
I'm glad you found the fix, apologies as the new database is in alpha so changes coming to it quite quickly.

**Comment by vkerrysingh** [comment]
Same issue, --node-id worked.

**Comment by suyashcjoshi** [comment]
Updated sample code so this is now fixed. Thanks for pointing it everyone :)

**Comment by Danie10** [comment]
Nope the .env code file still shows writwer1 for me - and this threw me about too. There seems to be a problem with the syncing of fixes back to teh code, which can confuse new users like me.
